DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    PROFESSION VARCHAR(50),
    LOCATION_X INT,
    LOCATION_Y INT,
    COMPANY_ORG VARCHAR(100),
    COMPANY_HQ VARCHAR(100)
);
